### ISSUE TITLE
Typescript issues with dev server and Playwright plugin

### ISSUE THREAD

**Issue by bp41** [Bielik20/nx-plugins#22]
Hello, thanks for the plugins. 

I'm trying to get an e2e project up and running to test one of my apps in my nx workspace. it's based on your `nx-jest-playwright` plugin.

The e2e executor takes a `devServerTarget` option (`myapp:serve`). When I attempt to run the e2e executor, Webpack runs the dev server and chokes on some Typescript syntax sugar features like the `??` operator and the fancy numeric separators like `7_600_000_000`. The funny thing is that running `nx serve myapp` doesn't cause any issues for Webpack.

Is there a way to fix this through the configuration? Should I wait for you to merge https://github.com/Bielik20/nx-plugins/pull/21 and hope that this solves the problem?

**Comment by Bielik20** [comment]
Hmm, yeah, I was going to say it may be because on NX 12.4.0 and update to jest major version.
I did address some of the issues in that PR, but I am afraid it may be yet another issue :/ 
I will release alpha version for you. I would recommend generating new e2e project to test if new configuration works.

**Comment by Bielik20** [comment]
If you could be so kind and test it: https://github.com/Bielik20/nx-plugins/releases/tag/v1.0.0-alpha-nx-12-4.1

**Comment by Bielik20** [comment]
I did test it in with fresh e2e project and it works fine. You can simply install this alpha version with npm/yarn. Let me know if it works fine for you.

**Comment by bp41** [comment]
Hi Damian. Thanks for the help and for pushing the pre-release so I could test this. I regenerated the e2e project using the alpha version. Unfortunately, it doesn't work - I'm still getting the same errors.

In the short term, I think I can still use Playwright but I had to take out the dev-server out of the e2e executor and now I have to start it up manually from another terminal. I will have to find a way to streamline this for my CI environment. 

Do you have any idea of what could be the root cause for this? I saw that you fire up the dev server using some nx internals, maybe it doesn't get the correct `tsconfig` or has the `target` inside of it misconfigured/overridden somehow?

**Comment by Bielik20** [comment]
Hmm, running dev server is heavily inspired by the way NX does that for cypress. That's why I am using some internal stuff. Actually I am surprised it doesn't work. I have tested it Saturday WITH devServerTarget on NextJS application and it worked without problems. What type of app do you run? React, nextjs, angular?
