### ISSUE TITLE
nx-serverless - Lambda layers 

### ISSUE THREAD

**Issue by EcksDy** [Bielik20/nx-plugins#48]
Hey @Bielik20 , thank you for your work! 🥇 

I have a question regarding nx-serverless plugin and layers.
My setup includes puppeteer-core and a lambda layer - [chrome-aws-lambda-layer](https://github.com/shelfio/chrome-aws-lambda-layer), and I'm describing it in the the .serverless config in the generated app. I also installed [chrome-aws-lambda](https://github.com/alixaxel/chrome-aws-lambda) as a devDependency.

Currently when I run deploy it tries to bundle the devDependency chrome-aws-lambda.
Is there a way I can exclude it from the package/deploy command as it should be available at runtime?

**Comment by Bielik20** [comment]
Hi, thanks for reaching out. I will assume that you are using [serverless-bundle](https://www.npmjs.com/package/serverless-bundle) which is added by default generator settings. In that case I would look into its docs because it handles bundling. You are probably looking for: https://www.npmjs.com/package/serverless-bundle#externals but I haven't tested it.

If you are using [@ns3/nx-serverless/plugin](https://github.com/Bielik20/nx-plugins/tree/master/packages/nx-serverless#ns3nx-serverlessplugin) which is still very much experimental (there may be breaking changes without a major version bump etc.) then you can just add dependencies you don't want to bundle to `externalDependencies` like in any other `@nrwl/node:webpack`: https://github.com/Bielik20/argus/blob/7b267026a297aa42647a392c1a5801f8e2539609/apps/api/project.json#L22

**Comment by EcksDy** [comment]
Hey, 
thank you for your quick response :)
I was actually using `@ns3/nx-serverless/plugin` and made the exclusion work via `externalDependencies`, so the original issue was solved.

Then unfortunately I couldn't make serverless pack some raw files(prisma schema/engine) into the lambda zip, even using custom `webpack.config.js` with the `webpack-copy-plugin`. 
So I've tried the default `serverless-bundle` and got it to work after some configuration.

Thank you for your time, this helped me solve an unrelated but frustrating issue :)
