### ISSUE TITLE
nx run mylib:deploy not forwarding attribute

### ISSUE THREAD

**Issue by chrizza87** [Bielik20/nx-plugins#55]
Hello,

thanks for the hard work upfront.

I updated nx today with the migrate functionality described on the nx webpage.

After that my serverless deploy command is not working. (`nx run mylib:deploy  --stage develop`).

I looked into the commands that are called and found:
``` nx runmylib:deploy --stage develop

> nx run mylib:package

Running: npx sls package
Environment: darwin, node 16.13.0, framework 3.19.0 (local), plugin 6.2.2, SDK 4.3.2
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Cannot resolve serverless.yml: Variables resolution errored with:
```

The attribute stage in not forwarded anymore, which worked before the update. I also tried it with 
`nx runmylib:deploy --stage=develop`, but the error is the same.

Package versions:
```
"@nrwl/angular": "14.4.3",
"@nrwl/cli": "14.4.3",
"@nrwl/eslint-plugin-nx": "14.4.3",
"@nrwl/jest": "14.4.3",
"@nrwl/linter": "14.4.3",
"@nrwl/nest": "14.4.3",
"@nrwl/node": "14.4.3",
"@nrwl/workspace": "14.4.3",
"@ns3/nx-serverless": "^3.0.0",
"serverless": "^3.18.2",
"serverless-bundle": "^5.4.0",
"serverless-domain-manager": "^6.0.3",
"serverless-mongodb-local": "^1.5.1",
"serverless-offline": "^8.8.0",
"serverless-webpack": "^5.8.0",
```

Do I need to change the call for the deployment or is this a bug?

Thanks in advance!

Greetz
Chrizza

**Comment by Puppo** [comment]
Hi [chrizza87](https://github.com/chrizza87),
I had the same problem.

To fix the problem:
 - update NX to the latest version
 - change the deploy configuration by adding the "params" property with the value "forward", like that:
```json
"deploy": {
      "executor": "@ns3/nx-serverless:sls",
      "outputs": ["apps/api/.serverless", "dist/apps/api"],
      "dependsOn": [
        {
          "target": "package",
          "projects": "self",
          "params": "forward" <-- HERE! 
        }
      ],
      "options": {
        "command": "deploy",
        "package": ".serverless",
        "buildTarget": "api:build:production"
      }
    }
```

The problem is relative to this [PR](https://github.com/nrwl/nx/pull/11103/commits/4cef2d1a8327f4a3e011ea028fb07e3faa8ee0c5)

I hope this can help you!

**Comment by chrizza87** [comment]
Hey @Puppo,

I inserted the params option in my config und it worked instantly :-)

Thank you very much, now everything is back to normal!

Have a nice evening/night

**Comment by chrizza87** [comment]
Hey @Puppo ,

i was too fast and it was probably to late yesterday :-D

I called `nx run mylibr:package --stage=develop` instead of `nx run mylibr:deploy --stage=develop` (was in my console "cache")

When i call `nx run mylibr:deploy --stage=develop`, the param still isn't forwarded to the package command ```nx run mylib:deploy --stage=develop 

> nx run mylibr:package

Running: npx sls package
```

Same goes for `--stage develop``

**Comment by Bielik20** [comment]
I did report that in here: https://github.com/nrwl/nx/issues/11014 and it is apparently released.

Still I have a long standing Issue on Nx repo where I wanted to address it _properly_. You can also take a look and maybe give it some more voice: https://github.com/nrwl/nx/issues/9034

There is nothing a can really do about Nx not passing args, sorry :(

**Comment by chrizza87** [comment]
Okay thx for the insights. i will comment the linked issues

No problem, we are using serverless command now as a workaround for now instead of nx

**Comment by Puppo** [comment]
Hi @chrizza87,
you have the same problem I had yesterday :) 

I notice you have the NX version 14.4.3, the same one I had yesterday :) 
I had to migrate NX to version 14.5.0 to fix the problem, adding then the `params` property said [before](https://github.com/Bielik20/nx-plugins/issues/55#issuecomment-1198642943)

You could try to migrate to the new version and test if the problem was fixed :) about 10 minutes at most it's the wasted time I think ;) 

Let me know if this is your solution too :)

**Comment by chrizza87** [comment]
Hey @Puppo,

Nx version update to 14.5.1 fixed the issue :-) now it works with your proposed solution.

Thank you very much!

**Comment by paulhobbel** [comment]
This is still an issue in newer versions of NX, maybe the `forward` attribute should be added during app generation

**Comment by Bielik20** [comment]
@paulhobbel Yeah, I should probably add that to generator. The executor itself work fine now. We are using that in production without problem.

I am hesitant to update generator now because I am toying with the idea of moving `--stage` to process.ENV. With env variables there is no issue with passing args, we can use `targetDefaults` to take it into the account for cache validation and can be used across many targets like e2e tests etc.

Still I haven't tested it properly yet but once I do I will update generator.
