### ISSUE TITLE
nx g @ns3/nx-serverless:app change my dependency

### ISSUE THREAD

**Issue by kang-heewon** [Bielik20/nx-plugins#68]
I found "updateDependencies" in the @ns3/nx-serverless:init generator. I agree that I need that behavior, but the version should be able to use the version I want. And if you necessarily need more than a specific version, it should be declared as a peerDependency. Also, if I'm already using a version higher than that, the function shouldn't lower my version.

I'm considering creating a pull request if needed. I'd love to hear back from you!

**Comment by Bielik20** [comment]
Hello, yeah, I agree. I would welcome a PR, let's make it so it doesn't lower a version if there is already a higher one 👍

**Comment by nponeccop** [comment]
As of now, it pins a single nx version in package.json:

https://github.com/Bielik20/nx-plugins/commit/a6a920cd3fea8edafaf624da0d466c25158453fa#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

So if there is a big repo and you want to use serverless in one package you have to upgrade to 19.4.0 and stay there until `nx-serverless` updates.

Probably >= 18 will be enough for all nx-related packages, instead of the currect 19.4.0

**Comment by Bielik20** [comment]
Yeah, should be finally fixed in https://github.com/Bielik20/nx-plugins/pull/111

I thought it worked this way from the start. My mistake.

**Comment by nponeccop** [comment]
It isn't fixed by #111 as the carets are still gone. Now it's the same problem again `nx@20.4.0` is out but cannot be upgraded.

https://github.com/Bielik20/nx-plugins/commit/1771d041ee2081f84c434aff4b1e70cb022dbb9e#diff-f70e2491b2d86d706674e1fd8c0407fac95f33f5b341eba9e9a364322c12b294L21 - in this commit the carets are gone again

See also our discussion in #108 about how the current practice of pinning verisions in this plugin contradicts other non-nrwl plugins and other arguments
