### ISSUE TITLE
remove dependency @nrwl/tao in @ns3/nx-serverless

### ISSUE THREAD

**Issue by kang-heewon** [Bielik20/nx-plugins#69]
The nx version is very important in a monorepo. When the nrwl/tao version goes up, the nx library version goes up!
It would be nice to remove the nrwl/tao dependency or move it to a peerDependency so that we can better manage that.

**Comment by Bielik20** [comment]
Hello, help me understand what is the problem here? When you have a different version of Nx than let's say `@ns3/nx-serverless` npm will simply install both. One that you use, and this will be used for your operations, and one for `@ns3/nx-serverless`. It will deduplicate them if possible. They should be able to coexist together. Am I missing something?

**Comment by kang-heewon** [comment]
Sorry to bother you! Since I didn't have nrwl/tao in my repository, I got an error saying the nx version was wrong.

The error disappeared when I installed the nrwl/tao version according to the nx version I was using.

**Comment by Bielik20** [comment]
Hmm, that's odd. It (nrwl/tao) should be listed as dependency and installed for you. Can you share what package manager (npm, yarn, etc.)  and what version are you using?
