### ISSUE TITLE
error on nx-serverless build [v0.3.0]

### ISSUE THREAD

**Issue by DaveLo** [Bielik20/nx-plugins#7]
I'm getting 
> ERROR: Something went wrong in @nrwl/run-commands - Cannot read property 'root' of undefined

when I run a build, I duplicated the issue in a bare repo to make sure it wasn't something in my setup.

It looks as though the issue is already fixed in your main branch, would it be possible to push a patch release out for this?

**Comment by Bielik20** [comment]
Hi, that's an issue with NX 12 changing this method to require context. I will update it soon.

**Comment by DaveLo** [comment]
I can fix if for now in my local by referencing code from your main branch where it is also already fixed. Mostly just wanted to avoid messing around in the node_modules folder since the issue is solved just not released :) 

https://github.com/Bielik20/nx-plugins/blob/222398d69980d244b578d45a790ffe3c77d7670c/packages/nx-serverless/src/executors/build/executor.ts#L24-L32

**Comment by Bielik20** [comment]
Should be fixed in 0.3.1 now.
For the future I actually plan to drop custom executors and just use `run-commands` executor in `workspace.json`.
This would make so that this lib responsibility would only be generation of an appropriate structure. But If I do so, it will be a breaking change and a major version bump.
